name: Canada (East) Films Inc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50116
title: WELCOME TO CANADA (EAST) FILMS INC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#30221f'
    - '#bca74c'
    - '#a05035'
    - '#f0de56'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.45839305920526385
purpose: []
