name: Canada (East) Films Inc
favicon: null
layout_spectrum: 0.51019
typography_spectrum: 0.50116
title: WELCOME TO CANADA (EAST) FILMS INC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f90a0f'
    - '#6d676c'
    - '#420c10'
    - '#e96e73'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
